### PR TITLE
ECMS-7714 The file's path should be shortened with an ellipsis when i…

### PR DESCRIPTION
**Pull request by trongtt**
…t's too long

### CODE REVIEW

**Comment by trongtt** [comment]
Compared to PLF 4.4.x, UI has been changed and it was using javascript to show up the ellipsis. So this is considered as a behavior change.

BTW I tested on IE 11 and Edge, it's working for me. Could you please double check ? @boubaker

**Comment by boubaker** [comment]
> Compared to PLF 4.4.x

This is a new Feature introduced in 5.0 ([PLF-7684](https://jira.exoplatform.org/browse/PLF-7684)) So you should compare with 5.0.0-M34

**Comment by boubaker** [comment]
> BTW I tested on IE 11 and Edge, it's working for me. Could you please double check ?

Didn't work see attached image:
capture du 2018-01-17 10-58-57

**Comment by boubaker** [comment]
@alaameddeb can you help @trongtt on this please.

**Comment by trongtt** [comment]
@boubaker could you tell me how I can upload/show 2 images horizontally ? This is the case I didn't check.

**Comment by trongtt** [comment]
Rejected as this will be fixed by https://github.com/exodev/social/pull/319

**Pull request closed without merging**
